# Form implementation generated from reading ui file 'text_writer__.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3
from docx import Document

import sys

from datetime import datetime





import sys
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtPrintSupport import *
import docx2txt


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_Doc_Writer(object):
    def setupUi(self, Doc_Writer):
        Doc_Writer.setObjectName("Doc_Writer")
        Doc_Writer.resize(852, 956)
        Doc_Writer.showMaximized()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        Doc_Writer.setFont(font)
        Doc_Writer.setLayoutDirection(QtCore.Qt.LeftToRight)
        Doc_Writer.setAutoFillBackground(False)
        Doc_Writer.setStyleSheet("background-color: rgb(255, 255, 255);")
        Doc_Writer.setTabShape(QtWidgets.QTabWidget.Rounded)
        Doc_Writer.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(Doc_Writer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setStyleSheet("#frame_2{\n"
"border:none;\n"
"border-radius:4px;\n"
"background-color: rgb(34, 34, 34);\n"
"}\n"
"#frame_2:hover{\n"
"background-color: rgb(0, 0, 225);\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_4.setStyleSheet("border: 0.5px solid rgb(180, 180, 180);\n"
"border-radius: 3px;\n"
"background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fontComboBox = QtWidgets.QFontComboBox(self.frame_4)
        self.fontComboBox.setMinimumSize(QtCore.QSize(120, 20))
        self.fontComboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setStyleSheet(" border:none;\n"
"border-radius: 5px;\n"
"font: 12pt \"Segoe UI\";")
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout_8.addWidget(self.fontComboBox)
        self.spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox.setMinimumSize(QtCore.QSize(70, 25))
        self.spinBox.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet(" border:none;\n"
"border-radius: 5px;\n"
"font: 12pt \"Segoe UI\";")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_8.addWidget(self.spinBox)
        self.horizontalLayout_7.addWidget(self.frame_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(250, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("#pushButton{\n"
"font: 12pt \"Segoe UI\";\n"
"font-weight: 500;\n"
"background-color: white;\n"
"color: black; \n"
"border-radius: 4px;\n"
" border: 2px solid #008CBA;\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"  background-color: #008CBA;\n"
"  color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"font: 12pt \"Segoe UI\";\n"
"font-weight: 500;\n"
"background-color: white;\n"
"color: black; \n"
"border-radius: 4px;\n"
" border: 2px solid #008CBA;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"  background-color: #008CBA;\n"
"  color: white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"font: 12pt \"Segoe UI\";\n"
"font-weight: 500;\n"
"background-color: white;\n"
"color: black; \n"
"border-radius: 4px;\n"
" border: 2px solid #008CBA;\n"
"}\n"
"\n"
"#pushButton_3:hover {\n"
"  background-color: #008CBA;\n"
"  color: white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("#label{\n"
"background-color: rgb(85, 85, 255);\n"
"font: 18pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 3px;\n"
"}\n"
"#label:hover{\n"
"\n"
"    background-color: rgb(8, 24, 11);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setStyleSheet("#textEdit{border-radius: 5px;\n"
"font: 14pt \"Segoe UI\";\n"
"border-bottom: 1px solid rgb(85, 255, 0);\n"
"\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Doc_Writer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Doc_Writer)
        self.statusbar.setObjectName("statusbar")
        Doc_Writer.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Doc_Writer)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.toolBar.setFont(font)
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setAcceptDrops(False)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.LeftToolBarArea)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        Doc_Writer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actioncopy = QtWidgets.QAction(Doc_Writer)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncopy.setIcon(icon)
        self.actioncopy.setObjectName("actioncopy")
        self.actionLeft = QtWidgets.QAction(Doc_Writer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/left-align.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeft.setIcon(icon1)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtWidgets.QAction(Doc_Writer)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/right-align.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRight.setIcon(icon2)
        self.actionRight.setObjectName("actionRight")
        self.actionCenter = QtWidgets.QAction(Doc_Writer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("source/center-align.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter.setIcon(icon3)
        self.actionCenter.setObjectName("actionCenter")
        self.actionjustificar = QtWidgets.QAction(Doc_Writer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("source/justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionjustificar.setIcon(icon4)
        self.actionjustificar.setObjectName("actionjustificar")
        self.actionrecortar = QtWidgets.QAction(Doc_Writer)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("source/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionrecortar.setIcon(icon5)
        self.actionrecortar.setObjectName("actionrecortar")
        self.actionitalic = QtWidgets.QAction(Doc_Writer)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("source/italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionitalic.setIcon(icon6)
        self.actionitalic.setObjectName("actionitalic")
        self.actionunderline = QtWidgets.QAction(Doc_Writer)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("source/underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionunderline.setIcon(icon7)
        self.actionunderline.setObjectName("actionunderline")
        self.actionbold = QtWidgets.QAction(Doc_Writer)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("source/Negrito.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbold.setIcon(icon8)
        self.actionbold.setObjectName("actionbold")
        self.actioncolar = QtWidgets.QAction(Doc_Writer)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("source/colar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncolar.setIcon(icon9)
        self.actioncolar.setObjectName("actioncolar")
        self.actionAbrir_arquivo = QtWidgets.QAction(Doc_Writer)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("source/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir_arquivo.setIcon(icon10)
        self.actionAbrir_arquivo.setObjectName("actionAbrir_arquivo")
        self.toolBar.addAction(self.actioncolar)
        self.toolBar.addAction(self.actioncopy)
        self.toolBar.addAction(self.actionrecortar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLeft)
        self.toolBar.addAction(self.actionRight)
        self.toolBar.addAction(self.actionCenter)
        self.toolBar.addAction(self.actionjustificar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionitalic)
        self.toolBar.addAction(self.actionunderline)
        self.toolBar.addAction(self.actionbold)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbrir_arquivo)

        self.retranslateUi(Doc_Writer)
        QtCore.QMetaObject.connectSlotsByName(Doc_Writer)
        self.actionAbrir_arquivo.triggered.connect(self.open_file)
        self.actionLeft.triggered.connect(lambda : self.textEdit.setAlignment(Qt.AlignmentFlag.AlignLeft))

        self.actionRight.triggered.connect(lambda : self.textEdit.setAlignment(Qt.AlignmentFlag.AlignRight))

        self.actionCenter.triggered.connect(lambda : self.textEdit.setAlignment(Qt.AlignmentFlag.AlignCenter))

        self.actionjustificar.triggered.connect(lambda : self.textEdit.setAlignment(Qt.AlignmentFlag.AlignJustify))
        
        self.actioncolar.triggered.connect(self.textEdit.paste)
        self.actioncopy.triggered.connect(self.textEdit.copy)
        self.actionrecortar.triggered.connect(self.textEdit.cut)
        self.spinBox.setValue(18)
        self.fontComboBox.activated.connect(self.setFont)
        self.spinBox.valueChanged.connect(self.setFontSize)
        self.actionitalic.triggered.connect(self.italicText)
        self.actionunderline.triggered.connect(self.underlineText)
        self.actionbold.triggered.connect(self.boldText)
        self.pushButton_2.clicked.connect(self.save_doc)
        self.pushButton.clicked.connect(self.save_bd)
        self.pushButton_3.clicked.connect(self.save_pdf)
        
        self.retranslateUi(Doc_Writer)
        QtCore.QMetaObject.connectSlotsByName(Doc_Writer)
        self.retranslateUi(Doc_Writer)
        QtCore.QMetaObject.connectSlotsByName(Doc_Writer)
        #ok
    def setFontSize(self):
        value = self.spinBox.value()
        self.textEdit.setFontPointSize(value)  
        #ok
        
    def setFont(self):
        font = self.fontComboBox.currentText()
        print(font)

        self.textEdit.setCurrentFont(QFont('Arial'))    
        
        #ok
    def italicText(self):
        state = self.textEdit.fontItalic()
        self.textEdit.setFontItalic(not(state)) 
        #ok
    def underlineText(self):
        state = self.textEdit.fontUnderline()
        self.textEdit.setFontUnderline(not(state))   
        
    def boldText(self):
        if self.textEdit.fontWeight() != QFont.Bold:
            self.textEdit.setFontWeight(QFont.Bold)
            return
        self.textEdit.setFontWeight(QFont.Normal)
    def save_bd(self):
        dados = self.textEdit.toPlainText()
        print(dados)

        data_e_hora_atuais = datetime.now()
        data_atual = data_e_hora_atuais.strftime("%d/%m/%Y %H:%M")
            

        try:
                banco = sqlite3.connect('lembretes.db') 
                c = banco.cursor()
                try:
                        c.execute("INSERT INTO dados (lembretes,data)VALUES(?,?)",(dados, data_atual))
                        banco.commit() 
                        banco.close()
                        print("data inserted!!!")
                except AttributeError:  
                        banco.commit() 
                        banco.close()
                        print("data not inserted!!!")
                        self.label.setText("      Docx Writer           (Texto Salvo com Sucesso!)")
        except sqlite3.Error as erro:
                self.label.setText("      Docx Writer           (Ocorreu um erro ao tentar salvar tente novamente em 5 segundos!)")
                print("Error please try again: ",erro) 
                
    def save_pdf(self):
        f_name, _ = QFileDialog.getSaveFileName(None, "Save pdf file", "", "pdf Files (*.pdf),(*.doc)")
        print(f_name)

        if f_name != '':  # if name not empty
           printer = QPrinter(QPrinter.HighResolution)
           printer.setOutputFormat(QPrinter.PdfFormat)
           printer.setOutputFileName(f_name)
           self.textEdit.document().print_(printer) 
    def save_doc(self):
        from pdf2docx import Converter
        import os
        
        path_output = 'doc.pdf'
        printer = QPrinter(QPrinter.HighResolution)
        printer.setOutputFormat(QPrinter.PdfFormat)
        printer.setOutputFileName(path_output)
        self.textEdit.document().print_(printer) 
        try:
                f_name, _ = QFileDialog.getSaveFileName(None, "Save docx file", "", "Docx Files (*.docx)")
        
               
                cv = Converter(path_output)
 
                cv.convert(f_name)
                
                cv.close()
                import time
        
                self.label.setText(f"      Docx Writer           (Texto Salvo com Sucesso! -> {f_name})")
        except:
                pass
    def open_file(self):
        self.path, _ = QFileDialog.getOpenFileName(None, "Abrir arquivos de texto", '.', filter="All files (*)")

        try:

            text = docx2txt.process(self.path) # docx2txt

        except Exception as e:
            print(e)
        else:
            self.textEdit.setText(text)
            
    def retranslateUi(self, Doc_Writer):
        _translate = QtCore.QCoreApplication.translate
        Doc_Writer.setWindowTitle(_translate("Doc_Writer", "Writer"))
        self.pushButton.setText(_translate("Doc_Writer", "Salvar no Banco de Dados"))
        self.pushButton_2.setText(_translate("Doc_Writer", "DOCX"))
        self.pushButton_3.setText(_translate("Doc_Writer", "PDF"))
        self.label.setText(_translate("Doc_Writer", "      Docx Writer"))
        self.toolBar.setWindowTitle(_translate("Doc_Writer", "toolBar"))
        self.actioncopy.setText(_translate("Doc_Writer", "Copiar"))
        self.actionLeft.setText(_translate("Doc_Writer", "Esquerda"))
        self.actionRight.setText(_translate("Doc_Writer", "Direita"))
        self.actionCenter.setText(_translate("Doc_Writer", "Justificar"))
        self.actionjustificar.setText(_translate("Doc_Writer", "Centralizar"))
        self.actionrecortar.setText(_translate("Doc_Writer", "Recortar"))
        self.actionitalic.setText(_translate("Doc_Writer", "Itálico"))
        self.actionunderline.setText(_translate("Doc_Writer", "Sublinhado"))
        self.actionbold.setText(_translate("Doc_Writer", "Negrito"))
        self.actioncolar.setText(_translate("Doc_Writer", "Colar"))
        self.actionAbrir_arquivo.setText(_translate("Doc_Writer", "Abrir arquivo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Doc_Writer = QtWidgets.QMainWindow()
    ui = Ui_Doc_Writer()
    ui.setupUi(Doc_Writer)
    Doc_Writer.show()
    sys.exit(app.exec_())
